"""Rename a column in one of the tables

Revision ID: 9259a6edad0a
Revises: b701adb4ee94
Create Date: 2024-05-10 00:55:16.526681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9259a6edad0a'
down_revision: Union[str, None] = 'b701adb4ee94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text_area', sa.String(), nullable=True))
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'text_area')
    # ### end Alembic commands ###
